### ISSUE TITLE
3DL kcl's do not preview correctly

### ISSUE THREAD

**Issue by Souperman9** [KillzXGaming/Switch-Toolbox#275]
When selected, the preview window for 3D Land's kcl's do not display. They do export to objs correctly however.
[AquariumSwimStepA.zip](https://github.com/KillzXGaming/Switch-Toolbox/files/5100243/AquariumSwimStepA.zip)

**Comment by Souperman9** [comment]
The materials seem to be in a PA file, but there's barely any documentation for it and not really any tool that can use it.

**Comment by KillzXGaming** [comment]
Seems it uses material ids per triangle, so it's splits each one into a mesh causing some drawing issues (meshes with 3 vertices are skipped due to how meshes are rendered)

For now i merged them all into one model so it displays. Importing however will require this for now https://github.com/exelix11/TheFourthDimension

3DL uses bcsv, same format as galaxy. The collision codes are different but that other editor should be able to support them.
Support for those is planned in another update.
