### ISSUE TITLE
Some Bugs

### ISSUE THREAD

**Issue by LoomisFire** [KillzXGaming/Switch-Toolbox#6]
- Can't zoom out enough to see entire model 
- Can't clear workspace
- Crashes game when editing textures in it

**Comment by KillzXGaming** [comment]
If the zoom is too much your model is likely too big. However there are 2 things you can do, change in the settings the near distance to be increased or change the preview scale to be lower. 

Clearing workspace is a known issue. I plan on reworking memory management and how everything is optimized sometimes this week or next.

Crashing the game? Needs more details, maybe some sampler files of what you are importing. A note is that not all bfres rebuild (due to some possible hard coded limitations, like 2D Mario)
