### ISSUE TITLE
Request: convert wiiu to switch

### ISSUE THREAD

**Issue by theryex** [KillzXGaming/Switch-Toolbox#82]
Request support to add a convert option for sbfres/bfres from wiiU to switch files

**Comment by KillzXGaming** [comment]
The format has too many changes so it is impossible without alot of game specific hacky additions (Specifically for materials). Since it's just alot of trouble for what it's worth, i don't plan on it. It still can easily swap models as dae, and swap textures as dds to basically convert mods over to the switch very quickly so i don't see any reason. Animations are planned however, with skeletal animations already being swappable between platforms.
