### ISSUE TITLE
Generate Tangents/Bitangents adds a lot of vertices

### ISSUE THREAD

**Issue by roket333** [KillzXGaming/Switch-Toolbox#98]
If I replace a mesh and don't uncheck the "Generate Tangents/Bitangents" option, vertex count on an object increases anywhere from a few to over 3X
I recommend making the option disabled by default

**Comment by KillzXGaming** [comment]
Anything that uses normal maps require them, or else those would not display at all or correctly. They're used extremely often, so i find it necessary to keep it enabled to prevent some mods being broken. It shouldn't increase the vertex count at all, unless you mean the overall size? Since it does add additional buffers for each vertex.

**Comment by roket333** [comment]
It adds vertices according to the vertex counter in the program

**Comment by KillzXGaming** [comment]
Can you send a sample dae then? I've tried multiple models but none increase the vertex counter

**Comment by roket333** [comment]
I've sent a sample DAE in #99 that you can use to test this, may be another C4D exclusive problem

**Comment by KillzXGaming** [comment]
Alright fixed https://github.com/KillzXGaming/Switch-Toolbox/commit/8afae95e2cf869812b6c83b137e48e67d2f8e102
